# Generated by Django 6.1.2 on 2026-10-06 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sets', models.PositiveSmallIntegerField(default=3)),
                ('reps', models.CharField(max_length=64)),
                ('rest_seconds', models.PositiveIntegerField(default=45)),
                ('suggested_load', models.CharField(blank=True, default='', max_length=64)),
                ('tip', models.TextField(blank=True, default='')),
                ('focus', models.CharField(max_length=64)),
                ('place', models.CharField(choices=[('Casa', 'Casa'), ('Academia', 'Academia'), ('Ambos', 'Ambos')], default='Ambos', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('place', models.CharField(choices=[('Casa', 'Casa'), ('Academia', 'Academia')], max_length=20)),
                ('level', models.CharField(choices=[('Iniciante', 'Iniciante'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], max_length=20)),
                ('duration_min', models.PositiveSmallIntegerField()),
                ('calories', models.PositiveIntegerField(default=0)),
                ('focus', models.JSONField(blank=True, default=list)),
                ('equipment', models.JSONField(blank=True, default=list)),
                ('muscles', models.JSONField(blank=True, default=list)),
                ('safety', models.JSONField(blank=True, default=list)),
                ('tone', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_links', to='catalog.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='catalog.workout')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('workout', 'exercise')},
            },
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(related_name='workouts', through='catalog.WorkoutExercise', to='catalog.exercise'),
        ),
    ]
