# Generated by Django 6.1.2 on 2026-10-06 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=64)),
                ('date_label', models.CharField(max_length=64)),
                ('time_label', models.CharField(max_length=16)),
                ('duration_min', models.PositiveSmallIntegerField()),
                ('level', models.CharField(choices=[('Iniciante', 'Iniciante'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], max_length=20)),
                ('spots', models.PositiveIntegerField(default=40)),
                ('participants', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('live', 'live'), ('upcoming', 'upcoming'), ('recorded', 'recorded')], max_length=20)),
                ('tone', models.CharField(blank=True, default='', max_length=128)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='live.instructor')),
            ],
            options={
                'verbose_name_plural': 'live classes',
                'ordering': ['status', 'time_label'],
            },
        ),
        migrations.CreateModel(
            name='ClassReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='live.liveclass')),
            ],
            options={
                'unique_together': {('user', 'live_class')},
            },
        ),
    ]
