# Generated by Django 6.1.2 on 2026-10-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='stream_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
    ]
