# Generated by Django 6.1.2 on 2026-10-09 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseAssistRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('clarifying', 'clarifying'), ('ready', 'ready'), ('searching', 'searching'), ('answered', 'answered'), ('failed', 'failed')], default='ready', max_length=20)),
                ('interpretation', models.JSONField(blank=True, default=dict)),
                ('clarifying_question', models.TextField(blank=True, default='')),
                ('answer_text', models.TextField(blank=True, default='')),
                ('steps', models.JSONField(blank=True, default=list)),
                ('cautions', models.JSONField(blank=True, default=list)),
                ('personalized_from_profile', models.BooleanField(default=False)),
                ('health_caution', models.BooleanField(default=False)),
                ('search_status', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assist_requests', to='catalog.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_assist_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('url', models.URLField(max_length=1024)),
                ('authorship', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('consulted_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='assistant.exerciseassistrequest')),
            ],
            options={
                'ordering': ['consulted_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('exercise_key', models.CharField(db_index=True, max_length=128)),
                ('exercise_name', models.CharField(max_length=255)),
                ('muscle_group', models.CharField(blank=True, default='', max_length=64)),
                ('variation', models.CharField(blank=True, default='', max_length=128)),
                ('equipment', models.JSONField(blank=True, default=list)),
                ('level', models.CharField(blank=True, default='', max_length=40)),
                ('goal', models.CharField(blank=True, default='', max_length=64)),
                ('persona', models.CharField(choices=[('woman', 'woman'), ('man', 'man'), ('neutral', 'neutral')], default='neutral', max_length=20)),
                ('language', models.CharField(default='pt-BR', max_length=16)),
                ('duration_sec', models.PositiveSmallIntegerField(default=7)),
                ('media_url', models.URLField(blank=True, default='', max_length=1024)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('review', 'review'), ('approved', 'approved'), ('rejected', 'rejected')], default='draft', max_length=20)),
                ('prompt_version', models.CharField(blank=True, default='v1', max_length=64)),
                ('structured_script', models.JSONField(blank=True, default=list)),
                ('source_notes', models.JSONField(blank=True, default=list)),
                ('ai_generated', models.BooleanField(default=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_demos', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_demos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='exerciseassistrequest',
            name='matched_demo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_requests', to='assistant.exercisedemo'),
        ),
        migrations.CreateModel(
            name='DemoGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('persona', models.CharField(choices=[('woman', 'woman'), ('man', 'man'), ('neutral', 'neutral')], default='neutral', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('done', 'done'), ('failed', 'failed'), ('not_configured', 'not_configured')], default='pending', max_length=20)),
                ('safe_error', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='assistant.exerciseassistrequest')),
                ('demo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='assistant.exercisedemo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('useful', models.BooleanField(blank=True, null=True)),
                ('equipment_ok', models.BooleanField(blank=True, null=True)),
                ('prefer_shorter', models.BooleanField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assist_feedback', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='assistant.exerciseassistrequest')),
                ('demo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='assistant.exercisedemo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='exercisedemo',
            index=models.Index(fields=['exercise_key', 'status'], name='assistant_e_exercis_16ed5d_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisedemo',
            index=models.Index(fields=['status', 'level'], name='assistant_e_status_be3495_idx'),
        ),
    ]
