# Generated by Django 6.1.2 on 2026-10-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_exerciseassistrequest_consultedsource_exercisedemo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demogenerationjob',
            name='provider_job_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
